# Generated by Django 6.0 on 2025-12-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_address_district_alter_address_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="session_key",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
    ]
