# Generated by Django 6.0 on 2025-12-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_address_session_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
