# Generated by Django 6.0 on 2025-12-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_user_otp_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="otp_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
