# Generated by Django 6.0 on 2025-12-16 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_product_is_slider_product_is_top_rated"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productspecification",
            name="name",
        ),
        migrations.AddField(
            model_name="productspecification",
            name="attribute",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="specifications",
                to="catalog.productattribute",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children",
                to="catalog.category",
            ),
        ),
    ]
