# Generated by Django 6.0 on 2025-12-16 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_remove_productspecification_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productattributevalue",
            name="attribute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="values",
                to="catalog.productattribute",
            ),
        ),
        migrations.AlterField(
            model_name="variantattribute",
            name="attribute_value",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="catalog.productattributevalue",
            ),
        ),
    ]
