# Generated by Django 6.0 on 2025-12-17 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_productattributevalue_attribute_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="variantattribute",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="variantattribute",
            name="attribute",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="product_attribute_values",
                to="catalog.productattribute",
            ),
        ),
        migrations.AddField(
            model_name="variantattribute",
            name="color_code",
            field=models.CharField(
                blank=True,
                help_text="Hex color code for color attributes",
                max_length=7,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="variantattribute",
            name="value",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.RemoveField(
            model_name="variantattribute",
            name="attribute_value",
        ),
    ]
