# Generated by Django 6.0 on 2025-12-17 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_variantattribute_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="variantattribute",
            unique_together={("variant", "attribute")},
        ),
    ]
