# Generated by Django 6.0 on 2025-12-17 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_variantattribute_unique_together"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProductAttributeValue",
        ),
    ]
