# Generated by Django 6.0 on 2025-12-17 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_color"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="variantattribute",
            name="color_code",
        ),
        migrations.AddField(
            model_name="variantattribute",
            name="color",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="product_attribute_values",
                to="catalog.color",
            ),
        ),
    ]
