# Generated by Django 6.0 on 2025-12-17 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_remove_variantattribute_color_code_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="variantattribute",
            unique_together={("variant", "attribute", "value")},
        ),
        migrations.AlterField(
            model_name="variantattribute",
            name="color",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="product_attribute_values",
                to="catalog.color",
            ),
        ),
    ]
