# Generated by Django 6.0 on 2025-12-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_alter_variantattribute_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="height",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Height in mm",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="length",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Length in mm",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="width",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Width in mm",
                max_digits=8,
                null=True,
            ),
        ),
    ]
