# Generated by Django 6.0 on 2025-12-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_alter_product_height_alter_product_length_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariant",
            name="sku",
            field=models.CharField(
                blank=True, max_length=100, null=True, unique=True
            ),
        ),
    ]
