# Generated by Django 6.0 on 2025-12-17 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_alter_productvariant_sku"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_most_popular",
            field=models.BooleanField(default=False),
        ),
    ]
