# Generated by Django 6.0 on 2025-12-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0013_product_is_most_popular"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_featured",
            field=models.BooleanField(default=True),
        ),
    ]
