# Generated by Django 6.0 on 2025-12-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0014_category_is_featured"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_main_menu",
            field=models.BooleanField(default=False),
        ),
    ]
