# Generated by Django 6.0 on 2025-12-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0015_category_is_main_menu"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="bn_name",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
