# Generated by Django 6.0 on 2025-12-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0016_category_bn_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_free_shipping",
            field=models.BooleanField(default=False),
        ),
    ]
