# Generated by Django 6.0 on 2025-12-18 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="carts",
                to="locations.district",
            ),
        ),
    ]
