# Generated by Django 6.0 on 2025-12-18 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
        ("shipping", "0002_shippingsetting"),
    ]

    operations = [
        migrations.AddField(
            model_name="district",
            name="shipping_zone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="districts",
                to="shipping.shippingzone",
            ),
        ),
    ]
