# Generated by Django 6.0 on 2025-12-25 18:42

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "orders",
            "0002_order_session_key_alter_order_billing_address_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cod_charge",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=10
            ),
        ),
    ]
